### ISSUE TITLE
Load error on webtrees 2.1.8

### ISSUE THREAD

**Issue by RH67dev** [JustCarmen/webtrees-fancy-research-links#76]
Using version 2.3.1 breaks the individual page on webtrees 2.1.8
Error message
Too few arguments to function JustCarmen\Webtrees\Module\FancyResearchLinks\Plugin\OpenArchievenPlugin::researchLink(), 1 passed in …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml on line 42 and exactly 3 expected …/modules_v4/jc-fancy-research-links/plugins/OpenArchievenPlugin.php:27

**Comment by JustCarmen** [comment]
There were some problems with this specific webtrees release. I didn't test this module against that release. I went straight from webtrees 2.1.7 to 2.1.12 which is currently the latest.

Do you still have issues when using the latest webtrees release? I cannot reproduce it.

**Comment by RH67dev** [comment]
Yes also receive the error after upgrading to 2.1.12
You can check yourselves by going to https://www.onsverleden.eu/webtrees21/tree/bijlholt/individual/I213/Bernardus-Antonius-Boelens and face the error page

**Comment by RH67dev** [comment]
Ah did not notice that, removed it and now it works.

Thanks again for your support !
